# Generated by Django 5.2.3 on 2025-06-27 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('estado_civil', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='board.bucket')),
            ],
        ),
    ]
